#! /bin/bash

source utils.sh

./gluetun
echo "Attente DNS"
DNS=$(check_DNS)
if [ $? -eq 0 ]; then
  echo "DNS : $DNS"
else
  echo "Erreur : $DNS"
  exit 1
fi

./qbittorrent
./flaresolverr
./prowlarr
./radarr
./sonarr
./pyload